/**
 * cedears-meta.ts — Sector y capitalización bursátil aproximada por CEDEAR.
 *
 * Ninguno de los feeds (IOL / data912) trae sector ni market cap, así que el
 * mapa de calor usa este dataset estático (relevado 2026-07, sectores GICS
 * simplificados en español, cap en MILES DE MILLONES de USD — "billions").
 * La cap es aproximada a propósito: define el TAMAÑO RELATIVO de las celdas,
 * no un dato que se muestre como verdad de mercado. Refrescar de tanto en
 * tanto alcanza.
 *
 * Sólo los tickers mapeados acá entran al mapa — eso excluye automáticamente
 * las variantes en USD con ticker comprimido que el dedup genérico no
 * atrapa (GOGLD, PETRD, AKOBD, B.D, VAL3C, …) y los duplicados B3/ADR de la
 * misma empresa (se mapea el ADR; PETR3/VALE3/ITUB3 etc. quedan afuera).
 */

export interface CedearMeta {
  sector: string;
  capBn: number; // capitalización aprox. en miles de millones de USD
}

export const CEDEAR_META: Record<string, CedearMeta> = {
  // ── Tecnología ─────────────────────────────────────────────────────────
  AAPL: { sector: 'Tecnología', capBn: 4000 },
  MSFT: { sector: 'Tecnología', capBn: 3700 },
  NVDA: { sector: 'Tecnología', capBn: 4500 },
  AVGO: { sector: 'Tecnología', capBn: 1700 },
  TSM:  { sector: 'Tecnología', capBn: 1500 },
  ORCL: { sector: 'Tecnología', capBn: 850 },
  SMSN: { sector: 'Tecnología', capBn: 450 },
  ASML: { sector: 'Tecnología', capBn: 400 },
  PLTR: { sector: 'Tecnología', capBn: 380 },
  AMD:  { sector: 'Tecnología', capBn: 380 },
  SAP:  { sector: 'Tecnología', capBn: 330 },
  IBM:  { sector: 'Tecnología', capBn: 280 },
  CSCO: { sector: 'Tecnología', capBn: 280 },
  CRM:  { sector: 'Tecnología', capBn: 250 },
  MU:   { sector: 'Tecnología', capBn: 250 },
  ACN:  { sector: 'Tecnología', capBn: 220 },
  ADBE: { sector: 'Tecnología', capBn: 200 },
  INTC: { sector: 'Tecnología', capBn: 200 },
  NOW:  { sector: 'Tecnología', capBn: 200 },
  SHOP: { sector: 'Tecnología', capBn: 200 },
  UBER: { sector: 'Tecnología', capBn: 200 },
  QCOM: { sector: 'Tecnología', capBn: 190 },
  TXN:  { sector: 'Tecnología', capBn: 180 },
  ANET: { sector: 'Tecnología', capBn: 180 },
  AMAT: { sector: 'Tecnología', capBn: 160 },
  SONY: { sector: 'Tecnología', capBn: 160 },
  ARM:  { sector: 'Tecnología', capBn: 150 },
  PANW: { sector: 'Tecnología', capBn: 140 },
  LRCX: { sector: 'Tecnología', capBn: 130 },
  CRWD: { sector: 'Tecnología', capBn: 120 },
  ADI:  { sector: 'Tecnología', capBn: 120 },
  MSTR: { sector: 'Tecnología', capBn: 90 },
  MRVL: { sector: 'Tecnología', capBn: 80 },
  SNOW: { sector: 'Tecnología', capBn: 80 },
  INFY: { sector: 'Tecnología', capBn: 80 },
  MSI:  { sector: 'Tecnología', capBn: 75 },
  TEAM: { sector: 'Tecnología', capBn: 60 },
  CRWV: { sector: 'Tecnología', capBn: 60 },
  GLW:  { sector: 'Tecnología', capBn: 45 },
  GRMN: { sector: 'Tecnología', capBn: 40 },
  SNDK: { sector: 'Tecnología', capBn: 35 },
  HPQ:  { sector: 'Tecnología', capBn: 30 },
  ERIC: { sector: 'Tecnología', capBn: 30 },
  NOKA: { sector: 'Tecnología', capBn: 30 },
  VRSN: { sector: 'Tecnología', capBn: 30 },
  ZM:   { sector: 'Tecnología', capBn: 25 },
  NBIS: { sector: 'Tecnología', capBn: 25 },
  ALAB: { sector: 'Tecnología', capBn: 25 },
  TWLO: { sector: 'Tecnología', capBn: 20 },
  FSLR: { sector: 'Tecnología', capBn: 20 },
  ASX:  { sector: 'Tecnología', capBn: 20 },
  SWKS: { sector: 'Tecnología', capBn: 15 },
  DOCU: { sector: 'Tecnología', capBn: 15 },
  CLS:  { sector: 'Tecnología', capBn: 15 },
  IREN: { sector: 'Tecnología', capBn: 15 },
  HUT:  { sector: 'Tecnología', capBn: 10 },
  RIOT: { sector: 'Tecnología', capBn: 8 },
  PATH: { sector: 'Tecnología', capBn: 8 },
  GLOB: { sector: 'Tecnología', capBn: 8 },
  RGTI: { sector: 'Tecnología', capBn: 5 },
  AI:   { sector: 'Tecnología', capBn: 3 },
  BMNR: { sector: 'Tecnología', capBn: 3 },
  XROX: { sector: 'Tecnología', capBn: 2 },

  // ── Comunicaciones ─────────────────────────────────────────────────────
  GOOGL: { sector: 'Comunicaciones', capBn: 3400 },
  META:  { sector: 'Comunicaciones', capBn: 1900 },
  NFLX:  { sector: 'Comunicaciones', capBn: 450 },
  TMUS:  { sector: 'Comunicaciones', capBn: 280 },
  T:     { sector: 'Comunicaciones', capBn: 200 },
  DISN:  { sector: 'Comunicaciones', capBn: 200 },
  VZ:    { sector: 'Comunicaciones', capBn: 180 },
  SPOT:  { sector: 'Comunicaciones', capBn: 130 },
  RBLX:  { sector: 'Comunicaciones', capBn: 80 },
  NTES:  { sector: 'Comunicaciones', capBn: 70 },
  AMX:   { sector: 'Comunicaciones', capBn: 55 },
  EA:    { sector: 'Comunicaciones', capBn: 45 },
  TCOM:  { sector: 'Comunicaciones', capBn: 45 },
  BIDU:  { sector: 'Comunicaciones', capBn: 40 },
  VOD:   { sector: 'Comunicaciones', capBn: 25 },
  PINS:  { sector: 'Comunicaciones', capBn: 25 },
  WBO:   { sector: 'Comunicaciones', capBn: 25 },
  VIV:   { sector: 'Comunicaciones', capBn: 18 },
  TIMB:  { sector: 'Comunicaciones', capBn: 15 },
  SNAP:  { sector: 'Comunicaciones', capBn: 15 },
  ROKU:  { sector: 'Comunicaciones', capBn: 12 },
  JOYY:  { sector: 'Comunicaciones', capBn: 2 },
  YELP:  { sector: 'Comunicaciones', capBn: 2 },
  TRIP:  { sector: 'Comunicaciones', capBn: 2 },
  TV:    { sector: 'Comunicaciones', capBn: 2 },

  // ── Consumo Discrecional ───────────────────────────────────────────────
  AMZN: { sector: 'Consumo Discrecional', capBn: 2500 },
  TSLA: { sector: 'Consumo Discrecional', capBn: 1500 },
  HD:   { sector: 'Consumo Discrecional', capBn: 400 },
  BABA: { sector: 'Consumo Discrecional', capBn: 320 },
  TM:   { sector: 'Consumo Discrecional', capBn: 300 },
  MCD:  { sector: 'Consumo Discrecional', capBn: 220 },
  PDD:  { sector: 'Consumo Discrecional', capBn: 180 },
  BKNG: { sector: 'Consumo Discrecional', capBn: 180 },
  TJX:  { sector: 'Consumo Discrecional', capBn: 140 },
  MELI: { sector: 'Consumo Discrecional', capBn: 130 },
  SE:   { sector: 'Consumo Discrecional', capBn: 110 },
  SBUX: { sector: 'Consumo Discrecional', capBn: 110 },
  NKE:  { sector: 'Consumo Discrecional', capBn: 100 },
  RACE: { sector: 'Consumo Discrecional', capBn: 90 },
  ABNB: { sector: 'Consumo Discrecional', capBn: 80 },
  ORLY: { sector: 'Consumo Discrecional', capBn: 80 },
  GM:   { sector: 'Consumo Discrecional', capBn: 60 },
  JD:   { sector: 'Consumo Discrecional', capBn: 55 },
  HMC:  { sector: 'Consumo Discrecional', capBn: 55 },
  ROST: { sector: 'Consumo Discrecional', capBn: 50 },
  F:    { sector: 'Consumo Discrecional', capBn: 45 },
  LVS:  { sector: 'Consumo Discrecional', capBn: 40 },
  EBAY: { sector: 'Consumo Discrecional', capBn: 35 },
  CCL:  { sector: 'Consumo Discrecional', capBn: 35 },
  STLA: { sector: 'Consumo Discrecional', capBn: 30 },
  XPEV: { sector: 'Consumo Discrecional', capBn: 20 },
  DECK: { sector: 'Consumo Discrecional', capBn: 15 },
  CAR:  { sector: 'Consumo Discrecional', capBn: 12 },
  NIO:  { sector: 'Consumo Discrecional', capBn: 8 },
  ETSY: { sector: 'Consumo Discrecional', capBn: 8 },
  ARCO: { sector: 'Consumo Discrecional', capBn: 6 },
  ANF:  { sector: 'Consumo Discrecional', capBn: 5 },
  URBN: { sector: 'Consumo Discrecional', capBn: 5 },
  HOG:  { sector: 'Consumo Discrecional', capBn: 4 },
  GT:   { sector: 'Consumo Discrecional', capBn: 3 },
  JMIA: { sector: 'Consumo Discrecional', capBn: 1 },

  // ── Consumo Básico ─────────────────────────────────────────────────────
  WMT:   { sector: 'Consumo Básico', capBn: 850 },
  COST:  { sector: 'Consumo Básico', capBn: 450 },
  PG:    { sector: 'Consumo Básico', capBn: 400 },
  KO:    { sector: 'Consumo Básico', capBn: 300 },
  PM:    { sector: 'Consumo Básico', capBn: 260 },
  PEP:   { sector: 'Consumo Básico', capBn: 230 },
  UL:    { sector: 'Consumo Básico', capBn: 160 },
  FMX:   { sector: 'Consumo Básico', capBn: 130 },
  MO:    { sector: 'Consumo Básico', capBn: 100 },
  MDLZ:  { sector: 'Consumo Básico', capBn: 90 },
  CL:    { sector: 'Consumo Básico', capBn: 75 },
  DEO:   { sector: 'Consumo Básico', capBn: 70 },
  TGT:   { sector: 'Consumo Básico', capBn: 65 },
  KMB:   { sector: 'Consumo Básico', capBn: 45 },
  HSY:   { sector: 'Consumo Básico', capBn: 40 },
  SYY:   { sector: 'Consumo Básico', capBn: 40 },
  ABEV:  { sector: 'Consumo Básico', capBn: 30 },
  BNG:   { sector: 'Consumo Básico', capBn: 15 },
  KOFM:  { sector: 'Consumo Básico', capBn: 10 },
  AKO_B: { sector: 'Consumo Básico', capBn: 4 },
  NATU3: { sector: 'Consumo Básico', capBn: 3 },
  ADGO:  { sector: 'Consumo Básico', capBn: 1 },
  BIOX:  { sector: 'Consumo Básico', capBn: 0.5 },
  LND:   { sector: 'Consumo Básico', capBn: 0.5 },

  // ── Salud ──────────────────────────────────────────────────────────────
  LLY:   { sector: 'Salud', capBn: 800 },
  JNJ:   { sector: 'Salud', capBn: 400 },
  ABBV:  { sector: 'Salud', capBn: 380 },
  NVO:   { sector: 'Salud', capBn: 350 },
  UNH:   { sector: 'Salud', capBn: 280 },
  MRK:   { sector: 'Salud', capBn: 250 },
  ABT:   { sector: 'Salud', capBn: 230 },
  AZN:   { sector: 'Salud', capBn: 230 },
  NVS:   { sector: 'Salud', capBn: 230 },
  TMO:   { sector: 'Salud', capBn: 200 },
  ISRG:  { sector: 'Salud', capBn: 200 },
  AMGN:  { sector: 'Salud', capBn: 160 },
  PFE:   { sector: 'Salud', capBn: 150 },
  DHR:   { sector: 'Salud', capBn: 150 },
  GILD:  { sector: 'Salud', capBn: 140 },
  MDT:   { sector: 'Salud', capBn: 120 },
  VRTX:  { sector: 'Salud', capBn: 120 },
  BMY:   { sector: 'Salud', capBn: 110 },
  CVS:   { sector: 'Salud', capBn: 90 },
  CI:    { sector: 'Salud', capBn: 90 },
  GSK:   { sector: 'Salud', capBn: 80 },
  CAH:   { sector: 'Salud', capBn: 35 },
  BIIB:  { sector: 'Salud', capBn: 20 },
  MRNA:  { sector: 'Salud', capBn: 15 },
  HIMS:  { sector: 'Salud', capBn: 10 },
  TEM:   { sector: 'Salud', capBn: 10 },
  HAPV3: { sector: 'Salud', capBn: 2 },

  // ── Financiero ─────────────────────────────────────────────────────────
  BRKB:  { sector: 'Financiero', capBn: 1050 },
  JPM:   { sector: 'Financiero', capBn: 800 },
  V:     { sector: 'Financiero', capBn: 650 },
  MA:    { sector: 'Financiero', capBn: 550 },
  BAC:   { sector: 'Financiero', capBn: 350 },
  WFC:   { sector: 'Financiero', capBn: 260 },
  GS:    { sector: 'Financiero', capBn: 220 },
  AXP:   { sector: 'Financiero', capBn: 220 },
  MS:    { sector: 'Financiero', capBn: 210 },
  BX:    { sector: 'Financiero', capBn: 200 },
  HSBC:  { sector: 'Financiero', capBn: 180 },
  SCHW:  { sector: 'Financiero', capBn: 170 },
  C:     { sector: 'Financiero', capBn: 160 },
  SPGI:  { sector: 'Financiero', capBn: 160 },
  HDB:   { sector: 'Financiero', capBn: 160 },
  MUFG:  { sector: 'Financiero', capBn: 130 },
  IBN:   { sector: 'Financiero', capBn: 110 },
  MRSH:  { sector: 'Financiero', capBn: 110 },
  SAN:   { sector: 'Financiero', capBn: 100 },
  HOOD:  { sector: 'Financiero', capBn: 100 },
  BBV:   { sector: 'Financiero', capBn: 90 },
  FISV:  { sector: 'Financiero', capBn: 90 },
  COIN:  { sector: 'Financiero', capBn: 80 },
  USB:   { sector: 'Financiero', capBn: 70 },
  NU:    { sector: 'Financiero', capBn: 70 },
  PYPL:  { sector: 'Financiero', capBn: 70 },
  ITUB:  { sector: 'Financiero', capBn: 60 },
  ING:   { sector: 'Financiero', capBn: 60 },
  BCS:   { sector: 'Financiero', capBn: 60 },
  TRVV:  { sector: 'Financiero', capBn: 55 },
  LYG:   { sector: 'Financiero', capBn: 50 },
  AIG:   { sector: 'Financiero', capBn: 50 },
  MFG:   { sector: 'Financiero', capBn: 45 },
  XYZ:   { sector: 'Financiero', capBn: 45 },
  BSBR:  { sector: 'Financiero', capBn: 30 },
  KB:    { sector: 'Financiero', capBn: 25 },
  BBAS3: { sector: 'Financiero', capBn: 25 },
  NMR:   { sector: 'Financiero', capBn: 15 },
  AEG:   { sector: 'Financiero', capBn: 12 },
  XP:    { sector: 'Financiero', capBn: 8 },
  FNMA:  { sector: 'Financiero', capBn: 8 },
  UPST:  { sector: 'Financiero', capBn: 5 },
  STNE:  { sector: 'Financiero', capBn: 4 },
  PAGS:  { sector: 'Financiero', capBn: 3 },

  // ── Industrial ─────────────────────────────────────────────────────────
  GE:    { sector: 'Industrial', capBn: 200 },
  CAT:   { sector: 'Industrial', capBn: 200 },
  RTX:   { sector: 'Industrial', capBn: 160 },
  HON:   { sector: 'Industrial', capBn: 140 },
  UNP:   { sector: 'Industrial', capBn: 140 },
  DE:    { sector: 'Industrial', capBn: 130 },
  BA:    { sector: 'Industrial', capBn: 130 },
  HWM:   { sector: 'Industrial', capBn: 130 },
  ADP:   { sector: 'Industrial', capBn: 130 },
  LMT:   { sector: 'Industrial', capBn: 110 },
  MMM:   { sector: 'Industrial', capBn: 80 },
  FDX:   { sector: 'Industrial', capBn: 70 },
  JCI:   { sector: 'Industrial', capBn: 60 },
  PCAR:  { sector: 'Industrial', capBn: 55 },
  DAL:   { sector: 'Industrial', capBn: 40 },
  UAL:   { sector: 'Industrial', capBn: 35 },
  EFX:   { sector: 'Industrial', capBn: 30 },
  WEGE3: { sector: 'Industrial', capBn: 25 },
  SNA:   { sector: 'Industrial', capBn: 15 },
  AVY:   { sector: 'Industrial', capBn: 15 },
  RKLB:  { sector: 'Industrial', capBn: 15 },
  ASTS:  { sector: 'Industrial', capBn: 15 },
  PAC:   { sector: 'Industrial', capBn: 12 },
  AAL:   { sector: 'Industrial', capBn: 10 },
  ASR:   { sector: 'Industrial', capBn: 10 },
  EMBJ:  { sector: 'Industrial', capBn: 10 },
  CAAP:  { sector: 'Industrial', capBn: 3 },
  PBI:   { sector: 'Industrial', capBn: 2 },
  ONDS:  { sector: 'Industrial', capBn: 2 },
  SATL:  { sector: 'Industrial', capBn: 1 },
  SPCE:  { sector: 'Industrial', capBn: 0.2 },

  // ── Energía ────────────────────────────────────────────────────────────
  XOM:   { sector: 'Energía', capBn: 480 },
  CVX:   { sector: 'Energía', capBn: 280 },
  SHEL:  { sector: 'Energía', capBn: 220 },
  TTE:   { sector: 'Energía', capBn: 160 },
  COP:   { sector: 'Energía', capBn: 130 },
  BP:    { sector: 'Energía', capBn: 100 },
  PBR:   { sector: 'Energía', capBn: 90 },
  EQNR:  { sector: 'Energía', capBn: 70 },
  E:     { sector: 'Energía', capBn: 55 },
  SLB:   { sector: 'Energía', capBn: 55 },
  PSX:   { sector: 'Energía', capBn: 55 },
  OXY:   { sector: 'Energía', capBn: 45 },
  BKR:   { sector: 'Energía', capBn: 45 },
  HAL:   { sector: 'Energía', capBn: 25 },
  CCJ:   { sector: 'Energía', capBn: 25 },
  VIST:  { sector: 'Energía', capBn: 20 },
  TEN:   { sector: 'Energía', capBn: 20 },
  PRIO3: { sector: 'Energía', capBn: 8 },
  UGP:   { sector: 'Energía', capBn: 4 },
  GLNG:  { sector: 'Energía', capBn: 4 },
  GPRK:  { sector: 'Energía', capBn: 0.4 },

  // ── Materiales ─────────────────────────────────────────────────────────
  BHP:  { sector: 'Materiales', capBn: 130 },
  RIO:  { sector: 'Materiales', capBn: 110 },
  SCCO: { sector: 'Materiales', capBn: 90 },
  ECL:  { sector: 'Materiales', capBn: 70 },
  FCX:  { sector: 'Materiales', capBn: 60 },
  NEM:  { sector: 'Materiales', capBn: 60 },
  AEM:  { sector: 'Materiales', capBn: 60 },
  VALE: { sector: 'Materiales', capBn: 45 },
  B:    { sector: 'Materiales', capBn: 35 },
  DD:   { sector: 'Materiales', capBn: 30 },
  NUE:  { sector: 'Materiales', capBn: 30 },
  DOW:  { sector: 'Materiales', capBn: 25 },
  GFI:  { sector: 'Materiales', capBn: 25 },
  IP:   { sector: 'Materiales', capBn: 20 },
  IFF:  { sector: 'Materiales', capBn: 20 },
  HMY:  { sector: 'Materiales', capBn: 15 },
  KGC:  { sector: 'Materiales', capBn: 15 },
  CX:   { sector: 'Materiales', capBn: 15 },
  PAAS: { sector: 'Materiales', capBn: 12 },
  MP:   { sector: 'Materiales', capBn: 10 },
  MOS:  { sector: 'Materiales', capBn: 10 },
  SUZ:  { sector: 'Materiales', capBn: 10 },
  TXR:  { sector: 'Materiales', capBn: 10 },
  CDE:  { sector: 'Materiales', capBn: 8 },
  HL:   { sector: 'Materiales', capBn: 8 },
  GGB:  { sector: 'Materiales', capBn: 6 },
  NG:   { sector: 'Materiales', capBn: 5 },
  NXE:  { sector: 'Materiales', capBn: 3 },
  SID:  { sector: 'Materiales', capBn: 2 },
  LAC:  { sector: 'Materiales', capBn: 1 },
  BAK:  { sector: 'Materiales', capBn: 1 },
  MUX:  { sector: 'Materiales', capBn: 0.3 },

  // ── Servicios Públicos ─────────────────────────────────────────────────
  NEE:   { sector: 'Servicios Públicos', capBn: 160 },
  CEG:   { sector: 'Servicios Públicos', capBn: 100 },
  VST:   { sector: 'Servicios Públicos', capBn: 60 },
  NGG:   { sector: 'Servicios Públicos', capBn: 55 },
  OKLO:  { sector: 'Servicios Públicos', capBn: 20 },
  KEP:   { sector: 'Servicios Públicos', capBn: 12 },
  SBS:   { sector: 'Servicios Públicos', capBn: 10 },
  ELPC:  { sector: 'Servicios Públicos', capBn: 3 },

  // ── Inmobiliario ───────────────────────────────────────────────────────
  O: { sector: 'Inmobiliario', capBn: 50 },

  // ── ETFs (tamaño = AUM aprox., mismo criterio de área) ─────────────────
  SPY:  { sector: 'ETFs', capBn: 600 },
  IVV:  { sector: 'ETFs', capBn: 550 },
  QQQ:  { sector: 'ETFs', capBn: 300 },
  VEA:  { sector: 'ETFs', capBn: 140 },
  GLD:  { sector: 'ETFs', capBn: 100 },
  IEMG: { sector: 'ETFs', capBn: 90 },
  VIG:  { sector: 'ETFs', capBn: 90 },
  IJH:  { sector: 'ETFs', capBn: 90 },
  IWM:  { sector: 'ETFs', capBn: 70 },
  RSP:  { sector: 'ETFs', capBn: 70 },
  XLK:  { sector: 'ETFs', capBn: 70 },
  IBIT: { sector: 'ETFs', capBn: 60 },
  EFA:  { sector: 'ETFs', capBn: 55 },
  IVW:  { sector: 'ETFs', capBn: 50 },
  XLF:  { sector: 'ETFs', capBn: 50 },
  DIA:  { sector: 'ETFs', capBn: 35 },
  IVE:  { sector: 'ETFs', capBn: 35 },
  XLE:  { sector: 'ETFs', capBn: 35 },
  XLV:  { sector: 'ETFs', capBn: 35 },
  SMH:  { sector: 'ETFs', capBn: 25 },
  TQQQ: { sector: 'ETFs', capBn: 25 },
  ACWI: { sector: 'ETFs', capBn: 20 },
  XLI:  { sector: 'ETFs', capBn: 20 },
  XLC:  { sector: 'ETFs', capBn: 20 },
  XLY:  { sector: 'ETFs', capBn: 20 },
  EEM:  { sector: 'ETFs', capBn: 18 },
  EWJ:  { sector: 'ETFs', capBn: 18 },
  XLU:  { sector: 'ETFs', capBn: 18 },
  GDX:  { sector: 'ETFs', capBn: 15 },
  SLV:  { sector: 'ETFs', capBn: 15 },
  XLP:  { sector: 'ETFs', capBn: 15 },
  ESGU: { sector: 'ETFs', capBn: 15 },
  ETHA: { sector: 'ETFs', capBn: 10 },
  EWY:  { sector: 'ETFs', capBn: 8 },
  CIBR: { sector: 'ETFs', capBn: 8 },
  ARKK: { sector: 'ETFs', capBn: 7 },
  FXI:  { sector: 'ETFs', capBn: 7 },
  IBB:  { sector: 'ETFs', capBn: 6 },
  XLRE: { sector: 'ETFs', capBn: 6 },
  XLB:  { sector: 'ETFs', capBn: 5 },
  SPHQ: { sector: 'ETFs', capBn: 5 },
  SPXL: { sector: 'ETFs', capBn: 5 },
  IEUR: { sector: 'ETFs', capBn: 5 },
  EWZ:  { sector: 'ETFs', capBn: 4 },
  URA:  { sector: 'ETFs', capBn: 4 },
  ICLN: { sector: 'ETFs', capBn: 3 },
  ILF:  { sector: 'ETFs', capBn: 2 },
  COPX: { sector: 'ETFs', capBn: 2 },
  XME:  { sector: 'ETFs', capBn: 2 },
  USO:  { sector: 'ETFs', capBn: 1 },
  PSQ:  { sector: 'ETFs', capBn: 1 },
  SH:   { sector: 'ETFs', capBn: 1 },
  VXX:  { sector: 'ETFs', capBn: 1 },
};

// El feed usa "AKO.B"; las keys de objeto con punto son válidas pero mejor
// resolver por lookup explícito.
export function cedearMeta(symbol: string): CedearMeta | undefined {
  if (symbol === 'AKO.B') return CEDEAR_META['AKO_B'];
  return CEDEAR_META[symbol];
}
